### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by nicolasdelfino** [lequanghuylc/react-native-video-to-gif#1]
Hi! Im looking for something that could allow me to make a gif from an array of base64 data (treated as frames). Do you think that your lib is suited as a base for this idea?

**Comment by lequanghuylc** [comment]
My lib does only one thing: Convert local video file to gif. You can use other lib to convert your input into video, and then use  this lib to do the rest. But it's not a good idea since we can convert directly from frames to gif.
